---
title: "git_01"
author: "Omar Monreal"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
They sought it with thimbles, they sought it with care;  
They pursued it with forks and hope;  
They threatened its life with a railway-share;  
They charmed it with smiles and soap.  
They shuddered to think that the chase might fail,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Whose woods these are I think I know.  
His house is in the village though;  
He will not see me stopping here  
To watch his woods fill up with snow.  
  
My little horse must think it queer  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Do not go gentle into that good night,  
Old age should burn and rave at close of day;  
Rage, rage against the dying of the light.  
  
Though wise men at their end know dark is right,  
Because their words had forked no lightning they  
Do not go gentle into that good night.  
  
Good men, come on it the last wave by, crying how bright  
Their frail deeds might have danced in a green bay,  
Rage, rage against the dying of the light.  
  
Wild men who caught and sang the sun in flight,  
And learn, too late, they grieved it on its way,  
Do not go gentle into that good night.  
  
Grave men, near death, who see with blinding sight  
Blind eyes could blaze like meteors and be gay,  
Rage, rage against the dying of the light.  
  
And you, my father, there on that sad height,  
Curse, bless, me now with your fierce tears, I pray.  
Do not go gentle into that good night.  
Rage, rage against the dying of the light.  